// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using PruebaClaro_UWP.Model.Data.SQLite;
using System;

namespace PruebaClaro_UWP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180423124952_Claro")]
    partial class Claro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("PruebaClaro_UWP.Model.Data.SQLite.Entities.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Actor");

                    b.Property<string>("Clasificacion");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Director");

                    b.Property<string>("Duracion");

                    b.Property<string>("Escritor");

                    b.Property<string>("Genero");

                    b.Property<string>("Productor");

                    b.Property<string>("Titulo");

                    b.Property<string>("TítuloOriginal");

                    b.Property<string>("UrlImagen");

                    b.HasKey("Id");

                    b.ToTable("Pelicula");
                });
#pragma warning restore 612, 618
        }
    }
}
